apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ricardo-sandbox-app
  namespace: argocd
spec:
  project: streamlit-apps
  source:
    repoURL: https://gitlab.com/oceanum/config/streamlit-apps.git
    path: ricardo-sandbox
    targetRevision: HEAD
  destination:
    namespace: knative-services
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
    syncOptions:     # Sync options which modifies sync behavior
    - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
